// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXLzT3URwj6ELRotk9vL9YyIQ9B4dXr9I',
    appId: '1:350639232772:web:0fd7e97595bdbb8f376251',
    messagingSenderId: '350639232772',
    projectId: 'pack-tookang',
    authDomain: 'pack-tookang.firebaseapp.com',
    storageBucket: 'pack-tookang.appspot.com',
    measurementId: 'G-J10S6SM48F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTgPMJ2jwwqkP3VQj3F50HTDvoc8NseHE',
    appId: '1:350639232772:android:9a88461dcaeb4644376251',
    messagingSenderId: '350639232772',
    projectId: 'pack-tookang',
    storageBucket: 'pack-tookang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwbL2uwcdrJ4JtDimZvgb9I5DSpR2Nhw',
    appId: '1:350639232772:ios:f817067ccf85995e376251',
    messagingSenderId: '350639232772',
    projectId: 'pack-tookang',
    storageBucket: 'pack-tookang.appspot.com',
    iosBundleId: 'com.example.packTookang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCwbL2uwcdrJ4JtDimZvgb9I5DSpR2Nhw',
    appId: '1:350639232772:ios:f817067ccf85995e376251',
    messagingSenderId: '350639232772',
    projectId: 'pack-tookang',
    storageBucket: 'pack-tookang.appspot.com',
    iosBundleId: 'com.example.packTookang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXLzT3URwj6ELRotk9vL9YyIQ9B4dXr9I',
    appId: '1:350639232772:web:b11a2ead6657dc85376251',
    messagingSenderId: '350639232772',
    projectId: 'pack-tookang',
    authDomain: 'pack-tookang.firebaseapp.com',
    storageBucket: 'pack-tookang.appspot.com',
    measurementId: 'G-EH4T8S8RML',
  );
}
